### ISSUE TITLE
GradleClassPathResolver task needs to depend on assemble

### ISSUE THREAD

**Issue by twicksell** [atomist/list-used-api#12]
The GradleClassPathResolver gradle task needs to depend on assemble. This ensures that any project level dependencies are built and available on the filesystem.

**Comment by lievendoclo** [comment]
We can't put a dependency in the script, because if the java plugin is not applied in the init script, you cannot set a dependency to the `assemble` goal. It's only known in the body of the `doLast`, and there you cannot set a dependency (because you're already in goal execution at that point).
I however am now calling assemble directly, as this tool only works for Java projects anyway, so the `assemble` goal should be available explicitly.

**Comment by twicksell** [comment]
Resolved
